### ISSUE TITLE
Struggling to run

### ISSUE THREAD

**Issue by msinton** [smithandrewl/fractals#3]
After cloning the repo (and setting up clang etc). I run `sbt run` and get the following error:

```
[info] Compiling to native code (735 ms)
[error] /usr/bin/ld: cannot find -lSDL2
[error] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[info] Linking native code (boehm gc) (14 ms)
java.io.IOException: Cannot run program "/home/me/git/test/fractals/target/scala-2.11/fractals-out": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) java.io.IOException: Cannot run program "/home/me/git/test/fractals/target/scala-2.11/fractals-out": error=2, No such file or directory
```
Am I doing something wrong?
I am able to run a hello world project using ScalaNativePlugin

**Comment by msinton** [comment]
I found the problem. I needed to install sdl-ttf also `sudo apt-get install libsdl2-ttf-dev`
